/**
 * Generator — emits `__generated__/routes.ts` from a list of {@link ScannedRoute}s.
 *
 * The generated module statically imports every `routes.ts` so that bundlers
 * (esbuild/tsup) can tree-shake unused dependencies and Cloud Functions get
 * the smallest possible cold-start footprint.
 */

import { dirname, join } from "node:path";
import { mkdirSync, writeFileSync } from "node:fs";

import {
  derivePath,
  toImportSpecifier,
  type PathDeriveOptions,
} from "./path-utils";
import type { ScannedRoute } from "./scanner";

export interface GeneratorOptions {
  /** Absolute path of the file to write (e.g. `…/__generated__/routes.ts`). */
  outFile: string;
  /** Path-derivation options (skipSegments, casing). */
  derive: PathDeriveOptions;
  /**
   * Import extension used in the generated file:
   * - `".js"` (default) — required for ESM Node.js with `"type": "module"`,
   * - `""`               — bundler-friendly (Vite, no extension),
   * - `".ts"`            — for TS-ESM runners (`tsx`, `bun`).
   */
  importExtension: string;
  /** Friendly banner placed at the top of the generated file. */
  banner?: string;
  /** Generation timestamp included in the banner. Default: `new Date()`. */
  now?: Date;
}

export const DEFAULT_GENERATOR_BANNER =
  "/**\n" +
  " * AUTO-GENERATED by `@lpdjs/firestore-repo-service` Hono codegen.\n" +
  " * Do not edit by hand — re-run `hono:gen` after adding / removing route files.\n" +
  " */\n";

export interface GenerationResult {
  /** Absolute path of the file written. */
  outFile: string;
  /** Number of routes captured in the manifest. */
  routeCount: number;
  /** Human-readable summary of the derived URLs. */
  derivedPaths: { source: string; url: string }[];
}

export function generateRoutesManifest(
  routes: ScannedRoute[],
  opts: GeneratorOptions,
): GenerationResult {
  const outDir = dirname(opts.outFile);
  mkdirSync(outDir, { recursive: true });

  const banner = opts.banner ?? DEFAULT_GENERATOR_BANNER;
  const now = (opts.now ?? new Date()).toISOString();
  const ext = opts.importExtension;

  const importLines: string[] = [];
  const entryLines: string[] = [];
  const derivedPaths: GenerationResult["derivedPaths"] = [];

  routes.forEach((r, i) => {
    const importPath = toImportSpecifier(outDir, r.absPath, ext);
    const url = derivePath(r.relDir, opts.derive);
    importLines.push(
      `import mod${i} from ${JSON.stringify(importPath)};`,
    );
    entryLines.push(`  { __derivedPath: ${JSON.stringify(url)}, mod: mod${i} },`);
    derivedPaths.push({ source: r.relPath, url });
  });

  const body =
    `${banner}` +
    `// Generated at ${now} — ${routes.length} route file${routes.length === 1 ? "" : "s"}.\n` +
    `\n` +
    `import type { AnyRouteDef, RouteModuleDefault } from "@lpdjs/firestore-repo-service/servers/hono";\n` +
    `\n` +
    importLines.join("\n") +
    (importLines.length ? "\n\n" : "\n") +
    `const __defs: { __derivedPath: string; mod: RouteModuleDefault }[] = [\n` +
    entryLines.join("\n") +
    (entryLines.length ? "\n" : "") +
    `];\n\n` +
    `export const routes: AnyRouteDef[] = __defs.flatMap(({ __derivedPath, mod }) => {\n` +
    `  const list = Array.isArray(mod) ? mod : [mod];\n` +
    `  return list.map((route) => ({ ...route, path: route.path ?? __derivedPath }));\n` +
    `});\n`;

  writeFileSync(opts.outFile, body, "utf8");
  return {
    outFile: opts.outFile,
    routeCount: routes.length,
    derivedPaths,
  };
}

/** Convenience helper used by the CLI — combines scan + generate in one call. */
export function generateFromRoot(
  rootAbs: string,
  outFileRel: string,
  derive: PathDeriveOptions,
  importExtension: string,
  scan: (root: string) => ScannedRoute[],
): GenerationResult {
  const routes = scan(rootAbs);
  const outFile = join(rootAbs, outFileRel);
  return generateRoutesManifest(routes, {
    outFile,
    derive,
    importExtension,
  });
}
