/**
 * AUTO-GENERATED by `@lpdjs/firestore-repo-service` Hono codegen.
 * Do not edit by hand — re-run `hono:gen` after adding / removing route files.
 */
// Generated at 2026-05-10T22:49:52.903Z — 3 route files.

import type { AnyRouteDef, RouteModuleDefault } from "@lpdjs/firestore-repo-service/servers/hono";

import mod0 from "../posts/useCases/createPost/routes.js";
import mod1 from "../posts/useCases/getPost/routes.js";
import mod2 from "../posts/useCases/listPosts/routes.js";

const __defs: { __derivedPath: string; mod: RouteModuleDefault }[] = [
  { __derivedPath: "/posts/createPost", mod: mod0 },
  { __derivedPath: "/posts/getPost", mod: mod1 },
  { __derivedPath: "/posts/listPosts", mod: mod2 },
];

export const routes: AnyRouteDef[] = __defs.flatMap(({ __derivedPath, mod }) => {
  const list = Array.isArray(mod) ? mod : [mod];
  return list.map((route) => ({ ...route, path: route.path ?? __derivedPath }));
});
