import type { RequestContext } from "@lpdjs/firestore-repo-service/servers/hono";

/**
 * HubspotService — generated by `frs add service hubspot`.
 *
 * Registered with a factory in `services.ts`. Async SDK clients should be
 * lazy-loaded inside the class to keep cold-starts fast.
 */
export class HubspotService {
  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
  constructor(private readonly ctx: RequestContext) {}

  hello(): string {
    return `hello from hubspot`;
  }
}
