import type { RequestContext } from "@lpdjs/firestore-repo-service/servers/hono";
import { repos } from "..";

/**
 * RepositoryService — generated by `frs add service repository`.
 *
 * Registered with a factory in `services.ts` so dependencies are
 * destructured at registration time. Add new constructor parameters here
 * and update the factory line in `services.ts` accordingly — TypeScript
 * will tell you when something is missing.
 */
export class RepositoryService {
  // eslint-disable-next-line @typescript-eslint/no-useless-constructor
  constructor(private readonly ctx: RequestContext) {}

  get db() {
    return repos;
  }
}
